version: "3"

services:
  nginx-proxy:
    container_name: nginxproxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    container_name: demosite
    expose:
      - "80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=mc.jesuscm.dev
      - LETSENCRYPT_HOST=mc.jesuscm.dev
      - LETSENCRYPT_EMAIL=me@jesuscm.dev
    depends_on:
      - nginx-proxy
      - letsencrypt

  # # WORDPRESS
  # wordpress:
  #   image: wordpress:php7.4-apache
  #   environment:
  #     WORDPRESS_DB_HOST: mysql
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: mccactusdevs01
  #     WORDPRESS_DB_NAME: mccactusdevs
  #     VIRTUAL_HOST: mc.cactusdevs.tk
  #     LETSENCRYPT_HOST: mc.cactusdevs.tk
  #     LETSENCRYPT_EMAIL: me@jesuscm.dev
  #   links:
  #     - mysql:mysql
  #   volumes:
  #     - ./wordpress:/var/www/html
  #   depends_on:
  #     - nginx-proxy
  #     - letsencrypt
  # # MYSQL
  # mysql:
  #   image: mysql:8.0.13
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_DATABASE: mccactusdevs
  #     MYSQL_ROOT_PASSWORD: mccactusdevs01
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  # #MINIO
  # minio:
  #   image: minio/minio
  #   command: server /data
  #   expose:
  #     - 9000
  #   environment:
  #     MINIO_ACCESS_KEY: MINIOCACTUSDEVSACCESS
  #     MINIO_SECRET_KEY: MINIOCACTUSDEVSACCESSSECRET
  #     MINIO_DOMAIN: s3.cactusdevs.tk
  #     VIRTUAL_HOST: s3.cactusdevs.tk
  #     VIRTUAL_PORT: 9000
  #     LETSENCRYPT_HOST: s3.cactusdevs.tk
  #     LETSENCRYPT_EMAIL: me@jesuscm.dev
  #   volumes:
  #     - ./minio-data:/data
  # POSTE
  poste:
    image: analogic/poste.io:latest
    restart: unless-stopped
    container_name: mailserver
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    expose:
      - "80"
      - "443"

    volumes:
      - /usr/share/zoneinfo/America/Mexico_City:/etc/localtime:ro
      - ./poste/mail-data:/data
      - ./nginx/htmlnginx/html/.well-known:/opt/www/.well-known
      - ./poste/mail/etc/spamassassin/local.cf:/etc/spamassassin/local.cf

    environment:
      - LETSENCRYPT_EMAIL=me@jesuscm.dev
      - LETSENCRYPT_HOST=mail.jesuscm.dev
      - VIRTUAL_HOST=mail.jesuscm.dev
      - HTTPS=ON
volumes:
  certs:
  html:
  vhostd:
  confd:
