version: "3"

services:
  nginx-proxy:
    container_name: nginxproxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginxproxy/certs:/etc/nginx/certs:ro
      - ./nginxproxy/vhostd:/etc/nginx/vhost.d
      - ./nginxproxy/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./nginxproxy/certs:/etc/nginx/certs:rw
      - ./nginxproxy/vhostd:/etc/nginx/vhost.d
      - ./nginxproxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    container_name: demosite
    expose:
      - "80"
    volumes:
      - ./demosite:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=mc.jesuscm.dev
      - LETSENCRYPT_HOST=mc.jesuscm.dev
      - LETSENCRYPT_EMAIL=me@jesuscm.dev
    depends_on:
      - nginx-proxy
      - letsencrypt

  # # WORDPRESS
  wordpress:
    image: wordpress:php7.4-apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: db_demo
      VIRTUAL_HOST: 1.jesuscm.dev
      LETSENCRYPT_HOST: 1.jesuscm.dev
      LETSENCRYPT_EMAIL: me@jesuscm.dev
    links:
      - mysql:mysql
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - nginx-proxy
      - letsencrypt
  # # MYSQL
  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_demo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  #MINIO
  minio:
    image: minio/minio
    command: server /data
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: MINIOCACTUSDEVSACCESS
      MINIO_SECRET_KEY: MINIOCACTUSDEVSACCESSSECRET
      MINIO_DOMAIN: s3.jesuscm.dev
      VIRTUAL_HOST: s3.jesuscm.dev
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: s3.jesuscm.dev
      LETSENCRYPT_EMAIL: me@jesuscm.dev
    volumes:
      - ./minio-data:/data
  # POSTE
  poste:
    image: analogic/poste.io
    restart: unless-stopped
    container_name: mailserver
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    expose:
      - "80"
      - "443"
    volumes:
      - /usr/share/zoneinfo/America/Mexico_City:/etc/localtime:ro
      - ./poste/mail-data:/data
      - ./nginxproxy/html/.well-known:/opt/www/.well-known
      - ./poste/mail/etc/spamassassin/local.cf:/etc/spamassassin/local.cf

    environment:
      - LETSENCRYPT_EMAIL=me@jesuscm.dev
      - LETSENCRYPT_HOST=mail.jesuscm.dev
      - VIRTUAL_HOST=mail.jesuscm.dev
      - HTTPS=OFF
volumes:
  nginxproxy:
  poste:
  vhostd:
  confd:
